const fs = require("fs");
const path = require("path");

const customProjects = JSON.parse(fs.readFileSync(path.resolve(__dirname, "../data/custom-projects.json"), "utf8"));

const truxifyId = "662dbbb3-6e77-42ef-99af-57273a1c36e1";
const otherIds = customProjects.filter(r => r.id !== truxifyId).map(r => r.id);

// 29 Projects definition aligned with Excel Sheet rows 1 to 29
const curatedProjects = [
  {
    row: 1,
    id: truxifyId,
    title: "Truxify – Broker-Free Freight Marketplace",
    adminName: "Kanish Jeba Mathew M",
    githubUrl: "https://github.com/KanishJebaMathewM/Truxify",
    description: "An open-source, broker-free freight marketplace connecting manufacturers directly with truck drivers for transparent pricing, live GPS tracking, and instant load bookings.",
    language: "Flutter",
    accentColor: "#FF7518",
    category: "Logistics & Supply Chain",
    iconType: "truck",
    tags: ["Flutter", "Dart", "Firebase", "Node.js", "Logistics", "Open Source"],
    stars: "40",
    forks: "195",
    openIssues: "1172",
    unassignedIssues: "655"
  },
  {
    row: 2,
    id: otherIds[0],
    title: "iloveAgents",
    adminName: "Aditthya SS Varma",
    githubUrl: "https://github.com/AditthyaSS/iloveAgents",
    description: "AI agents worth falling in love with. An open-source ecosystem of specialized autonomous agents built by the community and loved by everyone.",
    language: "JavaScript",
    accentColor: "#ec4899",
    category: "Machine Learning / AI",
    iconType: "sparkles",
    tags: ["JavaScript", "AI Agents", "Autonomous", "LLM", "Open Source"],
    stars: "117",
    forks: "200",
    openIssues: "137",
    unassignedIssues: "50"
  },
  {
    row: 3,
    id: otherIds[1],
    title: "adaptq",
    adminName: "Lakshmikanthan k",
    githubUrl: "https://github.com/l3tchupkt/adaptq",
    description: "High-performance C++17 KV cache compression and quantization engine for LLM inference with Python bindings, SIMD acceleration, and multi-backend edge deployment.",
    language: "C++",
    accentColor: "#10b981",
    category: "Systems & Low Level",
    iconType: "cpu",
    tags: ["C++", "LLM Inference", "KV Cache", "SIMD", "Quantization"],
    stars: "7",
    forks: "23",
    openIssues: "63",
    unassignedIssues: "20"
  },
  {
    row: 4,
    id: otherIds[2],
    title: "Bolcap",
    adminName: "Aditya Painuli",
    githubUrl: "https://github.com/AdityaPainuli/clippings-vids",
    description: "AI-powered viral-moment video clipping and Hinglish caption engine utilizing Whisper word-level transcription, customizable animated captions, and alpha overlay MOV exports.",
    language: "Python",
    accentColor: "#ef4444",
    category: "Video & Media",
    iconType: "video",
    tags: ["Python", "Whisper", "Video Processing", "AI/ML", "Hinglish"],
    stars: "4",
    forks: "18",
    openIssues: "93",
    unassignedIssues: "40"
  },
  {
    row: 5,
    id: otherIds[3],
    title: "PrepPilot",
    adminName: "Karan Manickam",
    githubUrl: "https://github.com/Canopus-Labs/PrepPilot",
    description: "An all-in-one interview preparation platform that helps candidates organize, track, practice mock interviews, and streamline their technical career preparation in one place.",
    language: "JavaScript",
    accentColor: "#3b82f6",
    category: "EdTech & Career Pathways",
    iconType: "layout",
    tags: ["JavaScript", "React", "EdTech", "Interview Prep", "Career"],
    stars: "23",
    forks: "142",
    openIssues: "8",
    unassignedIssues: "8"
  },
  {
    row: 6,
    id: otherIds[4],
    title: "Air Quality Intelligence Platform",
    adminName: "Aseem Prasad",
    githubUrl: "https://github.com/AseemPrasad/Air-Quality-Intelligence",
    description: "A local-first, open-source data engineering and analytics platform for real-time air-quality monitoring, anomaly detection, and near-term PM2.5 forecasting using sensor streams.",
    language: "Python",
    accentColor: "#059669",
    category: "Environmental & IoT",
    iconType: "leaf",
    tags: ["Python", "FastAPI", "Polars", "Data Engineering", "IoT", "Air Quality"],
    stars: "4",
    forks: "25",
    openIssues: "13",
    unassignedIssues: "1"
  },
  {
    row: 7,
    id: otherIds[5],
    title: "Secureflow",
    adminName: "Gaurav Karakoti",
    githubUrl: "https://github.com/GauravKarakoti/Secureflow",
    description: "AI-powered code security analysis platform integrating with GitHub pull requests to automatically detect vulnerabilities, security regressions, and provide instant remediation guidance.",
    language: "TypeScript",
    accentColor: "#6366f1",
    category: "Security & DevSecOps",
    iconType: "shield",
    tags: ["TypeScript", "Next.js", "Security", "DevSecOps", "AI Code Review"],
    stars: "10",
    forks: "79",
    openIssues: "8",
    unassignedIssues: "0"
  },
  {
    row: 8,
    id: otherIds[6],
    title: "AI Product Factory",
    adminName: "Logesh V",
    githubUrl: "https://github.com/logeshv586-code/AIproductfactory",
    description: "An open-source agentic platform helping developers and non-technical founders turn ideas into implementation-ready software specs, architectures, and runnable code through specialized AI agents.",
    language: "Python",
    accentColor: "#f43f5e",
    category: "Machine Learning / AI",
    iconType: "box",
    tags: ["Python", "TypeScript", "FastAPI", "Agentic AI", "Product Factory"],
    stars: "5",
    forks: "12",
    openIssues: "10",
    unassignedIssues: "2"
  },
  {
    row: 9,
    id: otherIds[7],
    title: "Harshal World",
    adminName: "Harshal",
    githubUrl: "https://github.com/harshalkurrey/Harshal-World",
    description: "An interactive web portal and arcade gaming showcase built for responsive browser exploration, engaging web utilities, and open-source frontend community collaboration.",
    language: "JavaScript",
    accentColor: "#f59e0b",
    category: "Developer Tools & Productivity",
    iconType: "layers",
    tags: ["JavaScript", "HTML5", "CSS3", "Frontend", "Game Development"],
    stars: "1",
    forks: "26",
    openIssues: "9",
    unassignedIssues: "9"
  },
  {
    row: 10,
    id: otherIds[8],
    title: "LinkID",
    adminName: "Kothakapu Vishnu Kiran",
    githubUrl: "https://github.com/vishnukothakapu/linkid",
    description: "A decentralized persistent identity protocol and developer toolkit ensuring unified link routing, verifiable creator credentials, and anti-link-rot infrastructure.",
    language: "TypeScript",
    accentColor: "#06b6d4",
    category: "Developer Tools & Productivity",
    iconType: "layers",
    tags: ["TypeScript", "Next.js", "Identity", "Decentralized", "Web3"],
    stars: "25",
    forks: "109",
    openIssues: "32",
    unassignedIssues: "10"
  },
  {
    row: 11,
    id: otherIds[9],
    title: "DevWhisper",
    adminName: "Aharshi Sinha",
    githubUrl: "https://github.com/Aharshi3614/Devwhisper",
    description: "Voice-first AI agent for developers. Instead of stopping to browse files or documentation, developers speak questions out loud and receive instant answers grounded in the local codebase.",
    language: "Python",
    accentColor: "#8b5cf6",
    category: "Developer Tools & Productivity",
    iconType: "terminal",
    tags: ["Python", "Voice AI", "Developer Tools", "Codebase Search", "LLM"],
    stars: "3",
    forks: "31",
    openIssues: "17",
    unassignedIssues: "5"
  },
  {
    row: 12,
    id: otherIds[10],
    title: "AthLead",
    adminName: "Harsh Vardhan",
    githubUrl: "https://github.com/Harsh-vardhan09/AthLead",
    description: "AI-powered sports talent discovery and national ranking platform built for the Ministry of Youth Affairs & Sports, identifying grassroots athletes through computer vision metrics.",
    language: "JavaScript",
    accentColor: "#10b981",
    category: "Data Science & Analytics",
    iconType: "trending-up",
    tags: ["JavaScript", "Computer Vision", "SportsTech", "Government AI", "Talent Discovery"],
    stars: "23",
    forks: "24",
    openIssues: "5",
    unassignedIssues: "5"
  },
  {
    row: 13,
    id: otherIds[11],
    title: "Workshpere",
    adminName: "Satyam Pandey",
    githubUrl: "https://github.com/SatyamPandey-07/WorkSphere",
    description: "Multi-agent AI workspace discovery platform that helps remote workers locate ideal cafes and coworking environments with noise levels, Wi-Fi speeds, and community ratings.",
    language: "TypeScript",
    accentColor: "#3b82f6",
    category: "Enterprise & Cloud",
    iconType: "layout",
    tags: ["TypeScript", "Next.js", "Multi-Agent AI", "Maps", "Remote Work"],
    stars: "18",
    forks: "77",
    openIssues: "212",
    unassignedIssues: "50"
  },
  {
    row: 14,
    id: otherIds[12],
    title: "Kiranawala",
    adminName: "Jyatin Kumar Singh",
    githubUrl: "https://github.com/Jyatin/KiranaWala",
    description: "Hyper-local grocery delivery and store management platform digitizing Indian neighborhood kirana shops with digital catalogs, inventory tracking, and direct customer ordering.",
    language: "JavaScript",
    accentColor: "#f97316",
    category: "Mobile & Web",
    iconType: "box",
    tags: ["JavaScript", "React", "Node.js", "E-Commerce", "Hyper-local", "Kirana"],
    stars: "0",
    forks: "1",
    openIssues: "0",
    unassignedIssues: "0"
  },
  {
    row: 15,
    id: otherIds[13],
    title: "TraffiTech",
    adminName: "Mohan Kumbar",
    githubUrl: "https://github.com/10-Mohan/Trafitech",
    description: "Smart traffic monitoring and urban congestion management platform leveraging computer vision and sensor analytics to optimize signal timing and reduce city road bottleneck delays.",
    language: "JavaScript",
    accentColor: "#eab308",
    category: "Environmental & IoT",
    iconType: "activity",
    tags: ["JavaScript", "IoT", "Traffic Management", "Smart Cities", "Analytics"],
    stars: "0",
    forks: "0",
    openIssues: "0",
    unassignedIssues: "0"
  },
  {
    row: 16,
    id: otherIds[14],
    title: "CreatorOS",
    adminName: "Aashutosh Kumar Bhardwaj",
    githubUrl: "https://github.com/aashutoshkumarbhardwaj/CreatorOs",
    description: "Open-source all-in-one business dashboard for digital creators, unifying bio links, direct message automation, customer relationships, revenue tracking, and content scheduling.",
    language: "JavaScript",
    accentColor: "#f43f5e",
    category: "Mobile & Web",
    iconType: "layout",
    tags: ["JavaScript", "Node.js", "Express", "Creator Economy", "CRM", "Automation"],
    stars: "42",
    forks: "92",
    openIssues: "72",
    unassignedIssues: "15"
  },
  {
    row: 17,
    id: otherIds[15],
    title: "DesktopAI",
    adminName: "Harsh Bansal",
    githubUrl: "https://github.com/Harshbansal8705/DesktopAI",
    description: "Voice-activated AI desktop assistant for Linux and desktop environments. Responds to custom wake words, executes terminal actions, launches apps, and provides intelligent contextual help.",
    language: "Python",
    accentColor: "#0284c7",
    category: "Developer Tools & Productivity",
    iconType: "cpu",
    tags: ["Python", "LangChain", "Voice Assistant", "Desktop", "Automation"],
    stars: "0",
    forks: "0",
    openIssues: "0",
    unassignedIssues: "0"
  },
  {
    row: 18,
    id: otherIds[16],
    title: "JuggadLang",
    adminName: "Sumangal Karan",
    githubUrl: "https://github.com/JugaadLang/jugaadlang",
    description: "A modern programming language crafted with Hindi keywords and Indian developer idioms. Write syntax the way you think, dream, and code with an interactive REPL and VS Code tooling.",
    language: "Python",
    accentColor: "#f97316",
    category: "Systems & Low Level",
    iconType: "terminal",
    tags: ["Python", "Compiler", "Language Design", "Hindi", "Developer Tools"],
    stars: "18",
    forks: "39",
    openIssues: "31",
    unassignedIssues: "0"
  },
  {
    row: 19,
    id: otherIds[17],
    title: "AI Stock Analyzer",
    adminName: "Akshay Kumar",
    githubUrl: "https://github.com/SrigadaAkshayKumar/stock",
    description: "Interactive financial analysis web application delivering technical charting, candlestick pattern recognition, and predictive machine learning models for equity forecasting.",
    language: "Python",
    accentColor: "#14b8a6",
    category: "Data Science & Analytics",
    iconType: "chart",
    tags: ["Python", "React", "Flask", "FinTech", "Machine Learning", "Stock Market"],
    stars: "37",
    forks: "108",
    openIssues: "55",
    unassignedIssues: "9"
  },
  {
    row: 20,
    id: otherIds[18],
    title: "PocketOps",
    adminName: "Aakarsh Singhal",
    githubUrl: "https://github.com/IIXII-L192/PocketOps-app",
    description: "Unified utility dashboard for Android hosting offline UPI QR generation, quick WhatsApp messaging, social shortcuts, and cloud developer utilities under open-source tooling.",
    language: "Kotlin",
    accentColor: "#6366f1",
    category: "Enterprise & Cloud",
    iconType: "server",
    tags: ["Kotlin", "Android", "Mobile", "Utilities", "UPI"],
    stars: "1",
    forks: "0",
    openIssues: "0",
    unassignedIssues: "0"
  },
  {
    row: 21,
    id: otherIds[19],
    title: "WalletWise",
    adminName: "Soumya Mishra",
    githubUrl: "https://github.com/SoumyaMishra-7/WalletWise",
    description: "Holistic personal finance platform combining automated budget analytics, behavioral spending insights, and AI-driven advisory to empower students and young professionals.",
    language: "JavaScript",
    accentColor: "#10b981",
    category: "Mobile & Web",
    iconType: "wallet",
    tags: ["JavaScript", "React", "FinTech", "Budgeting", "Personal Finance"],
    stars: "29",
    forks: "87",
    openIssues: "165",
    unassignedIssues: "19"
  },
  {
    row: 22,
    id: otherIds[20],
    title: "WinAurex",
    adminName: "Farhan Shaikh",
    githubUrl: "https://github.com/YTxFSGAMERz/WinAurex",
    description: "Comprehensive Windows performance optimization suite and telemetry debloater, delivering automated latency reductions, registry tuning, driver management, and privacy scripts.",
    language: "Batchfile",
    accentColor: "#a855f7",
    category: "Systems & Low Level",
    iconType: "shield",
    tags: ["Batchfile", "PowerShell", "Windows Optimization", "Performance", "Gaming"],
    stars: "7",
    forks: "0",
    openIssues: "1",
    unassignedIssues: "0"
  },
  {
    row: 23,
    id: otherIds[21],
    title: "hiero-bot-py",
    adminName: "Bhuvansh",
    githubUrl: "https://github.com/AnthropicBots/hiero-bot-py",
    description: "FastAPI-based GitHub maintainer automation bot streamlining repository workflows with PR health scoring, reviewer recommendations, issue triage, and live analytics dashboards.",
    language: "Python",
    accentColor: "#06b6d4",
    category: "Developer Tools & Productivity",
    iconType: "terminal",
    tags: ["Python", "FastAPI", "GitHub Bot", "Automation", "DevOps", "Open Source"],
    stars: "25",
    forks: "16",
    openIssues: "24",
    unassignedIssues: "10"
  },
  {
    row: 24,
    id: otherIds[22],
    title: "Dockfleet",
    adminName: "Pratyush Jha",
    githubUrl: "https://github.com/pratyushjha06/Dockfleet",
    description: "Free and open-source, local-first Docker container orchestration tool engineered for solo developers and small teams to deploy, monitor, and scale multi-service stacks on a single VPS.",
    language: "Python",
    accentColor: "#0284c7",
    category: "Enterprise & Cloud",
    iconType: "server",
    tags: ["Python", "FastAPI", "Docker", "DevOps", "Containers", "Self-Hosted"],
    stars: "14",
    forks: "29",
    openIssues: "9",
    unassignedIssues: "0"
  },
  {
    row: 25,
    id: otherIds[23],
    title: "TCalc — Local-First AI Coding Context & Token Intelligence Toolkit",
    adminName: "Sandesh Prakash Dawkhar",
    githubUrl: "https://github.com/Sandesh13fr/TCalc",
    description: "Local-first developer toolkit for analyzing repository token footprints, generating smart repo maps, optimizing model context windows, and integrating with Cursor, Claude Code, and MCP.",
    language: "TypeScript",
    accentColor: "#8b5cf6",
    category: "Developer Tools & Productivity",
    iconType: "calculator",
    tags: ["TypeScript", "LLM Context", "Tokenization", "MCP", "AI Tools"],
    stars: "15",
    forks: "16",
    openIssues: "35",
    unassignedIssues: "2"
  },
  {
    row: 26,
    id: otherIds[24],
    title: "Advanced Discord Bot",
    adminName: "Golla Bharath",
    githubUrl: "https://github.com/AdvancedDiscordBot/Advanced-Discord-Bot",
    description: "Feature-rich, community-focused Discord bot featuring Google Gemini AI conversation, automated moderation, interactive mini-games, dynamic XP leveling, and custom server plugins.",
    language: "JavaScript",
    accentColor: "#5865F2",
    category: "Developer Tools & Productivity",
    iconType: "sparkles",
    tags: ["JavaScript", "Node.js", "Discord.js", "Gemini AI", "Bot", "Gaming"],
    stars: "0",
    forks: "0",
    openIssues: "35",
    unassignedIssues: "15"
  },
  {
    row: 27,
    id: otherIds[25],
    title: "LixBlogs",
    adminName: "Vivek Yadav",
    githubUrl: "https://github.com/elixpo/blogs.elixpo",
    description: "Ultra-clean, modern publishing platform and markdown developer blogging engine built on Cloudflare edge workers, D1 databases, and Next.js for high-speed technical storytelling.",
    language: "JavaScript",
    accentColor: "#38bdf8",
    category: "Mobile & Web",
    iconType: "layers",
    tags: ["JavaScript", "Next.js", "Cloudflare", "Blogging", "Edge Computing"],
    stars: "10",
    forks: "10",
    openIssues: "21",
    unassignedIssues: "5"
  },
  {
    row: 28,
    id: otherIds[26],
    title: "CIVICFIX",
    adminName: "Janani B N",
    githubUrl: "https://github.com/Janani-bn/CivicFix",
    description: "Crowdsourced civic grievance reporting portal connecting citizens with municipal authorities for tracking potholes, sanitation, water shortages, and public infrastructure repairs.",
    language: "JavaScript",
    accentColor: "#10b981",
    category: "AI & Public Safety / CivicTech",
    iconType: "shield",
    tags: ["JavaScript", "CivicTech", "Citizen Portal", "Public Safety", "Municipal"],
    stars: "2",
    forks: "5",
    openIssues: "9",
    unassignedIssues: "0"
  },
  {
    row: 29,
    id: otherIds[27],
    title: "OpenHire",
    adminName: "Siddhartha Kushwaha",
    githubUrl: "https://github.com/DevSidd2006/openhire",
    description: "Transparent, open-source technical recruitment platform that matches candidates directly with engineering teams through verified skills, portfolio benchmarks, and fair assessment.",
    language: "Python",
    accentColor: "#f43f5e",
    category: "EdTech & Career Pathways",
    iconType: "box",
    tags: ["Python", "Recruitment", "Open Source Hiring", "Career", "Developer Jobs"],
    stars: "3",
    forks: "3",
    openIssues: "0",
    unassignedIssues: "0"
  }
];

module.exports = { curatedProjects };
